# Introduction

## Context

This project is focused on children's mental health in the United States, and the overarching goal is to comprehensively explore the intricate factors that potentially shape the mental well-being of children. We will apply data from NSCH (National Survey of Children's Health), which is a national household survey that collects different aspects of information regarding children's health.

## Motivation

Children's mental health is a subject of increasing concern in contemporary society, with growing awareness of the impact of early experiences on long-term mental and emotional outcomes. Mental health issues in childhood not only affect the individual child but can also have lasting effects into adulthood. Understanding the determinants of mental health in children is crucial for developing effective interventions and support systems. It carries public health significance, contributing to the overall understanding of mental health burdens, influencing families and communities, and informing evidence-based policies and programs.

## Research Questions

1.  The relationship between Children's mental health and Guardians' background: How do guardians' employment status affect children's mental health? Are children whose guardians have higher education more likely to have anxiety? Do children tend to have better mental health if their guardians have better mental health? How does Guardian's military experience influence children's mental status? Whether the age of Guardians and children serve as a potential factor of mental health issues?

2.  Children's experience and mental health: Are children more likely to be depressed if they have been treated unfairly because of gender identity or sexual orientation? How does being a victim of violence, living with people with alcohol problems, and experiencing parent divorce affect children's mental health respectively?

3.  Mutual effect of mental health problems on children: Do children who have one mental issue tend to suffer from other problems as well? How do other factors affect the number of mental illnesses children have?

4.  Relationship between physical health and mental health.
